### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by freed00m** [CZ-NIC/mininterface#1]
The website https://cz-nic.github.io/mininterface/ claims GPLv3.

However, there is not LICENSE.md in the repo.

**Comment by e3rd** [comment]
Hi! I hoped it's sufficient to place the license info into pyproject.toml. Do you think it is too little? If so, I try to keep as little files as possible, is it a bad idea to put it to README and not to add another file? :)

**Comment by freed00m** [comment]
It's missing License link in the github about 
![image](https://github.com/user-attachments/assets/d3fdd282-7130-4879-9ca1-1e4b0a8a6c2d)


![image](https://github.com/user-attachments/assets/39d0fb75-3d70-4785-90f8-adfe36ab7df1)

I think it would help SW analyzers and discoverability of this project or people who lurk on github to clearly see. 

I would have no idea to look inside into .toml file if I was searching for foss libraries.

**Comment by e3rd** [comment]
You are right, I've added a license file, it will appear with the next commit. Thanks for having this pointed out!
