### ISSUE TITLE
isn't gui supported with macOS?

### ISSUE THREAD

**Issue by sangshuduo** [CZ-NIC/mininterface#4]
I already installed the following packages.

```
pip install tyro typing_extensions pyyaml tkinter_form
```

However, I ran the example code but it still shows TUI in the terminal.

**Comment by e3rd** [comment]
Sorry, I must have missed this issue. 

Could you save this to a file and run it with `python3 file.py` so that we know whether tkinter (the default python gui library) is working properly on your system?

```python3
from tkinter import *
  
root = Tk() 
a = Label(root, text ="Hello World") 
a.pack() 
  
root.mainloop() 
```

**Comment by sangshuduo** [comment]
$ python ex1.py
Traceback (most recent call last):
  File "/Users/sangshuduo/work/python/miniinterface/ex1.py", line 1, in <module>
    from tkinter import *
  File "/opt/homebrew/Cellar/python@3.10/3.10.15/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'

$ python --version
Python 3.10.15

**Comment by e3rd** [comment]
Thanks for having tested!

Try `brew install python-tk` (according to https://stackoverflow.com/questions/68554782/ )

**Comment by sangshuduo** [comment]
it works now.

**Comment by e3rd** [comment]
Amazing, thanks, I'll add this to the readme.
